version: '2.2'

services:
  nginx:
    image: nginx
    container_name: ontaxi-nginx
    environment:
      TZ: "Asia/Ho_Chi_Minh"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginx_conf:/etc/nginx/conf.d
      - nginx_certs:/etc/nginx/certs
    depends_on:
      - hub
      - api
    restart: always
  hub:
    image: thold88/ontaxi-hub:1.0.0-SNAPSHOT
    container_name: ontaxi-hub
    environment:
      TZ: "Asia/Ho_Chi_Minh"
    depends_on:
      - mysql
  api:
    image: thold88/ontaxi-api:1.0.0-SNAPSHOT
    container_name: ontaxi-api
    environment:
      TZ: "Asia/Ho_Chi_Minh"
    depends_on:
      - mysql
  backup:
    image: thold88/ontaxi-backup:1.0.0
    tty: true
    container_name: ontaxi-backup
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    container_name: ontaxi-mysql
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "adm1n"
      MYSQL_DATABASE: "ontaxi"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "adm1n"
      TZ: "Asia/Ho_Chi_Minh"
    command: ["--max_allowed_packet=512M", "--innodb_log_file_size=200M"]
    restart: always
volumes:
  mysql_data:
    driver: local
  nginx_conf:
    driver: local
  nginx_certs:
    driver: local
