version: '2.2'

services:
  nginx:
    build:
      context: docker/nginx
    container_name: ontaxi-nginx
    environment:
      TZ: "Asia/Ho_Chi_Minh"
      PUID: 1000
      PGID: 1000
      URL: ontaxi.vn
      SUBDOMAINS: api,hub
      ONLY_SUBDOMAINS: "true"
      VALIDATION: http
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - hub
      - api
    restart: always
  hub:
    image: thold88/ontaxi-hub:1.0.0-SNAPSHOT
    container_name: ontaxi-hub
    environment:
      TZ: "Asia/Ho_Chi_Minh"
    depends_on:
      - mysql
  api:
    image: thold88/ontaxi-api:1.0.0-SNAPSHOT
    container_name: ontaxi-api
    environment:
      TZ: "Asia/Ho_Chi_Minh"
    depends_on:
      - mysql
  backup:
    image: thold88/mysql-s3-backup:1.0.0
    tty: true
    container_name: ontaxi-backup
    depends_on:
      - mysql
    environment:
      MYSQL_DATABASE: "ontaxi"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "adm1n"
      AWS_ACCESS_KEY_ID: "AKIAQFNFYMQHBMSXWIWK"
      AWS_SECRET_ACCESS_KEY: "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"
  mysql:
    image: mysql:5.7
    container_name: ontaxi-mysql
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "adm1n"
      MYSQL_DATABASE: "ontaxi"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "adm1n"
      TZ: "Asia/Ho_Chi_Minh"
    command: ["--max_allowed_packet=512M", "--innodb_log_file_size=200M"]
    restart: always
volumes:
  mysql_data:
    driver: local
  nginx_conf:
    driver: local
  nginx_certs:
    driver: local
