version: '2.2'

services:
  nginx:
    image: nginx
    ports:
      - "80:80"
    environment:
      - NGINX_PORT=80
    volumes:
      - nginx_data:/etc/nginx/conf
    depends_on:
      - hub
      - api
    restart: always
  hub:
    image: thold88/ontaxi-hub:1.0.0-SNAPSHOT
    environment:
      TZ: "Asia/Ho_Chi_Minh"
    depends_on:
      - mysql
    ports:
      - "8585:8080"
  api:
    image: thold88/ontaxi-api:1.0.0-SNAPSHOT
    environment:
      TZ: "Asia/Ho_Chi_Minh"
    depends_on:
      - mysql
    ports:
      - "8586:8080"
  mysql:
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "adm1n"
      MYSQL_DATABASE: "ontaxi"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "adm1n"
      TZ: "Asia/Ho_Chi_Minh"
    command: ["--max_allowed_packet=512M", "--innodb_log_file_size=200M"]
    restart: always
volumes:
  mysql_data:
    driver: local
  nginx_data:
    driver: local
