version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0.1-jdk

    working_directory: ~/backend
    steps:
      - checkout
      - run:
        name: Build and push docker images
        command: |
          echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
          mvn -P docker


