version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:8u171-jdk-stretch

    working_directory: ~/backend
    steps:
      - run: sudo apt-get install sshpass
      - checkout
      - setup_remote_docker
      - run: |
            echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
      - run: mvn initialize
      - run: mvn -P prod clean package
      - run: mvn -P docker
      - run: sshpass -p $SSH_PASSWORD ssh -o StrictHostKeyChecking=no admin@hub.ontaxi.vn -t "cd ~/sources/ontaxi;git pull"
      - run: sshpass -p $SSH_PASSWORD ssh -o StrictHostKeyChecking=no admin@hub.ontaxi.vn -t "cd ~/sources/ontaxi;docker pull thold88/ontaxi-hub:1.0.0-SNAPSHOT"
      - run: sshpass -p $SSH_PASSWORD ssh -o StrictHostKeyChecking=no admin@hub.ontaxi.vn -t "cd ~/sources/ontaxi;docker pull thold88/ontaxi-api:1.0.0-SNAPSHOT"
      - run: sshpass -p $SSH_PASSWORD ssh -o StrictHostKeyChecking=no admin@hub.ontaxi.vn -t "cd ~/sources/ontaxi;docker-compose up -d"
