version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:8u171-jdk-stretch

    working_directory: ~/backend
    steps:
      - checkout
      - setup_remote_docker
      - run: |
            echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
      - run: mvn initialize
      - run: mvn -P docker


