version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0.1-jdk

    working_directory: ~/backend
    steps:
      - checkout
      - setup_remote_docker
      - run: |
            echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
      - run: mvn -P docker


